layouts:
    - fullscreen
    - bsp
    # - middle-wide
    # - two-pane
    # - tall

mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

# Disable mod + <space>
cycle-layout:
    mod: <NONE>
    key: <NONE>

# Disable mod + n
focus-screen-cw:
    mod: <NONE>
    key: <NONE>

mouse-resizes-windows: true
# focus-follows-mouse: true
mouse-follows-focus: false

floating:
    # Find IDs with: osascript -e 'id of app "Google Chrome Beta"'
    - com.google.Chrome
    - com.google.Chrome.beta
    - com.google.Chrome.canary
    - com.1password.1password
    - com.apple.systempreferences
    - com.microsoft.VSCode
    - com.brnbw.Leader-Key
    - com.google.Chrome.app.apkjikbjlghbonboeaehkeoadefnfjmb # $HOME/Applications/Chrome Apps.localized/Cider.app
    - com.google.Chrome.app.fmgjjmmmlfnkbppncabfkddbjimcfncm # $HOME/Applications/Chrome Apps.localized/Gmail.app

toggle-focus-follows-mouse:
    mod: mod1
    key: x

select-bsp-layout:
    mod: mod1
    key: b
