layouts:
    - tall
    - fullscreen
    - middle-wide
    - bsp
    - two-pane

mod1:
    - option
    - shift
mod2:
    - option
    - shift
    - control

mouse-resizes-windows: true

floating:
    - com.google.Chrome
    - com.1password.1password
    - com.apple.systempreferences
    - com.microsoft.VSCode

toggle-focus-follows-mouse:
    mod: mod1
    key: x
