#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd)

set -e

echo ''

info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email? How about joech4n@users.noreply.github.com?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    success 'gitconfig'
  fi
}

setup_ohmyzsh () {
  if ! [ -d $HOME/.oh-my-zsh ]
  then
    info 'setup oh-my-zsh'
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    success 'oh-my-zsh'
  fi
}

setup_prezto () {
  if ! [ -d $HOME/.zprezto ]
  then
    info 'setup prezto'
    git clone --recursive git@github.com:joech4n/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
    success 'prezto'
  fi
}

install_dotfiles () {
  info 'installing dotfiles\n'
  stow -t ${HOME} stow
}

setup_vim () {
  info 'setting up vim'
}

# Required for other install-Darwin.sh scripts
install_homebrew () {
  info 'install homebrew'
  if ! command -v brew >/dev/null 2>&1
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" |tee /tmp/homebrew-install.log
    brew update
    brew upgrade
    success 'homebrew installed'
  else
    success 'skipping. homebrew already installed'
  fi
}

# Mac app store command line
install_mas () {
  info 'install mas'
  if ! command -v mas >/dev/null 2>&1
  then
    brew install mas
    success 'mas installed'
  else
    success 'skipping. mas already installed'
  fi
}

setup_fish () {
  info 'setup fish'
  if ! command -v fish >/dev/null 2>&1
  then
    brew install fish || sudo apt-get install -y fish || sudo yum install -y fish
    success 'fish installed'
  else
    success 'skipping. fish already installed'
  fi

  info 'cloning fish dotfiles'
  if [[ ! -d $HOME/.config/fish ]]; then
    git clone git@github.com:joech4n/fish-dotfiles.git $HOME/.config/fish
    success 'fish dotfiles cloned'
  else
    success 'skipping. fish dotfiles already cloned'
  fi
}

setup_zsh () {
  info 'adding /usr/local/bin/zsh to /etc/shells'
  if grep /usr/local/bin/zsh /etc/shells &> /dev/null ; then
    success 'skipping. /usr/local/bin/zsh already added to /etc/shells'
  else
    echo "/usr/local/bin/zsh" |sudo tee -a /etc/shells
    success 'added /usr/local/bin/zsh to /etc/shells'
  fi

  info 'setup zsh as default shell'
  if [ $SHELL != '/usr/local/bin/zsh' ]
  then
    echo
    chsh -s `which zsh`
    success 'zsh set as default shell'
  else
    success 'skipping. zsh already set as default shell'
  fi
}


install_dotfiles
# Must be first
if [ "$(uname)" == "Darwin" ]; then
  install_homebrew
  install_mas
  setup_zsh
fi
# If no args given run interactive stuff
if [ $# -eq 0 ]; then
    setup_gitconfig
fi
setup_prezto
install_dotfiles
setup_vim

echo ''
echo '  All installed!'
